-- Migration: expand project planning fields for CEO-driven project creation

BEGIN;

ALTER TABLE project
    RENAME COLUMN prj_description TO prj_source_brief;

ALTER TABLE project
    ADD COLUMN prj_definition_brief TEXT NOT NULL DEFAULT '',
    ADD COLUMN exe_id INTEGER REFERENCES execution(exe_id);

COMMENT ON COLUMN project.prj_source_brief IS 'Original brief provided by the human user';
COMMENT ON COLUMN project.prj_definition_brief IS 'Implementation-ready project definition generated by the CEO';
COMMENT ON COLUMN project.exe_id IS 'Execution that generated the current project plan';

CREATE INDEX IF NOT EXISTS idx_project_exe_id ON project(exe_id);

COMMIT;
